### ISSUE TITLE
줄리아 도서 번역자를 찾고 있습니다

### ISSUE THREAD

**Issue by anemochore** [juliakorea/translate-doc#15]
안녕하세요, 저는 한빛미디어에 근무하는 이상복이라고 합니다. 
국내에 제대로 된 줄리아 입문서가 없는 상황에서 
줄리아를 다루는 원서를 출간하기 위해 번역자를 찾고 있습니다. 
관심 있는 분들은 saerob@hanbit.co.kr 메일로 연락해주세요! 고맙습니다.

**Comment by wookay** [comment]
안녕하세요.
페이스북 그룹에도 글 남겨 주시면 좋을 것 같습니다.
https://www.facebook.com/groups/juliakorea

**Comment by anemochore** [comment]
넵 페북에 올렸습니다. ^^;
