### ISSUE TITLE
한국어 번역 기준이 필요한 것 같습니다.

### ISSUE THREAD

**Issue by ehgus** [juliakorea/translate-doc#16]
현재 한국어 번역 사이트의 문제점은 번역 기준이 모호하다는 것입니다. 예를 들어 "julia"를 영문 그대로 쓰는 경우와 "줄리아"라고 한글로 번역한 경우가 혼재하고 있고, 이외에도 높임말/낮춤말 혼재 현업에서 잘 사용하지 않는 번역투 문장도 가독성뿐만 아니라 앞으로 참여하게 될 번역자들에게 혼란을 줄 수 있을 것 같습니다. 혹시 관리자님은 이에 대해 어떤 의견을 가지고 계신가요?

**Comment by wookay** [comment]
저는 패키지 개발에 신경을 쓰고 있고. 전체적으로 매니징을 해 줄 분이 있으면 좋겠죠. 문서 번역은 많은 사람이 참여하게끔 하는게 목표입니다. 너무 까다롭지 않은, 참여하면서 즐거움을 줄 수 있으면 좋겠습니다.

**Comment by wookay** [comment]
juliakorea 슬랙 `#번역` 채널에도 공유해봅니다

**Comment by ehgus** [comment]
앗 slack 이 있는지 몰랐네요. 혹시 그룹 이름을 알 수 있을까요?

**Comment by wookay** [comment]
https://juliakorea.slack.com/ 이고    juliakorea 슬랙 가입하기 https://juliakorea-slack.herokuapp.com   에서 가입하시면 됩니다 :)
