### ISSUE TITLE
번역에 관하여

### ISSUE THREAD

**Issue by jin-park** [juliakorea/translate-doc#31]
안녕하세요, 시간이 좀 생겨서 번역을 해보려고 하는데 어디서부터 시작하면 좋을까요? 그리고 아직도 번역 프로젝트가 진행되고 있는 건가요?

감사합니다.

**Comment by ehgus** [comment]
안녕하세요, 많은 사람이 참여할수록 환영입니다! [번역하기](https://github.com/juliakorea/translate-doc/wiki/%EB%B2%88%EC%97%AD%ED%95%98%EA%B8%B0) 문서를 참고하시어 번역 프로젝트를 진행하시면 될 것입니다. 번역은 `src` 폴더에 있는 html 문서를 번역하시면 됩니다!

**Comment by jin-park** [comment]
그럼 일단 메뉴얼에 있는 문서들부터 해보도록 하겠습니다. 감사합니다!
